== Setting up an environment

Python 3 is required.

[source,bash]
....
python -m venv my_venv // <1>
source my_venv/bin/activate // <2>
pip install [-e] <path to this folder> // <3>
....
<1> the `venv` module creates a folder `my_venv` where you can play around as you like without messing with your system setup
<2> enable the `venv` (call `deactivate` to leave it)
<3> install desyrdl inside `my_venv`

== Running

See `desyrdl -h` for options. Below is an example for the test_hectare module which also comes with a testbench:

....
desyrdl -o out -i libraries/rdl/desyrdl_properties.rdl libraries/rdl/generic_ibus.rdl examples/spi_ad9510.rdl examples/test_hectare.rdl -f vhdl
....
This will compile each `.rdl` file, put together a register model and create one `.vhd` in `./out/` for each `addrmap` in the model and for each VHDL template in `./desyrdl/templates/`.

== Tests

The example above can be simulated in a self-checking testbench. It requires OSVVM and the ModelSim HDL Simulator.

....
cd tb/test_hectare/
vsim -c -do modelsim_do.tcl
....
